# Generated by Django 3.2.5 on 2021-07-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_categoria_produto_categoria_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_produto',
            new_name='preço_produto',
        ),
    ]
