# Generated by Django 3.2.5 on 2021-07-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_preco_produto_produto_preço_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria_produto',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='id_produto',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='marca_produto',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome_produto',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preço_produto',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='hora_resgistro_produto',
        ),
    ]
